package com.example.ui.util

enum class AppLanguage {
    TR, EN
}

object Loc {
    private val tr = mapOf(
        "home" to "Ana Sayfa",
        "library" to "Kütüphane",
        "miracles" to "Mucizeler",
        "dictionary" to "Sözlük",
        "search" to "Arama",
        "profile" to "Profil",
        "settings" to "Ayarlar",
        "appearance_settings" to "Görünüm Ayarları",
        "preview" to "ÖNİZLEME",
        "theme" to "TEMA",
        "light" to "Aydınlık",
        "dark" to "Karanlık",
        "sepia" to "Antik (Sepia)",
        "font_size" to "METİN BOYUTU",
        "font_family" to "YAZI TİPİ",
        "line_height" to "SATIR ARALIĞI",
        "tight" to "Dar",
        "normal" to "Orta",
        "wide" to "Geniş",
        "app_language" to "UYGULAMA DİLİ",
        "language_tr" to "Türkçe (TR)",
        "language_en" to "English (EN)",
        "daily_verse" to "GÜNÜN TEFEKKÜRÜ",
        "refresh_verse" to "Farklı Bir Ayet",
        "reading_history" to "Okuma Geçmişi",
        "notes_highlights" to "Notlar ve Vurgular",
        "stats" to "İSTATİSTİKLER",
        "pages_read" to "Okunan Ayet/Bölüm",
        "books_completed" to "Tamamlanan Kitaplar",
        "active_days" to "Aktif Gün Serisi",
        "all_scriptures" to "Kutsal Metinler",
        "quran" to "Kur'an-ı Kerim",
        "torah" to "Tevrat (Torah)",
        "gospel" to "İncil (Gospel)",
        "sermon" to "İncil",
        "bible" to "Kitab-ı Mukaddes",
        "search_hint" to "Ayet, sure, konu veya kelime ara...",
        "recent_searches" to "Son Aramalar",
        "clear" to "Temizle",
        "no_results" to "Sonuç bulunamadı",
        "search_results" to "Arama Sonuçları",
        "notes" to "Notlar",
        "highlights" to "Vurgular",
        "no_notes" to "Henüz eklenmiş bir not bulunmuyor.",
        "no_highlights" to "Henüz eklenmiş bir vurgu bulunmuyor.",
        "add_note" to "Not Ekle",
        "edit_note" to "Notu Düzenle",
        "save" to "Kaydet",
        "cancel" to "İptal",
        "delete" to "Sil",
        "read" to "Oku",
        "back" to "Geri",
        "all_verses_offline" to "Tüm Sureler Çevrimdışı!",
        "download_all_offline" to "Tüm Kitabı Çevrimdışı İndir",
        "quran_download_desc" to "114 surenin tamamı arapça ve türkçe mealleriyle cihaza kaydedildi. İnternetsiz okuyabilirsiniz.",
        "quran_download_promo" to "İslam'ın kutsal kitabı.",
        "downloading" to "İndiriliyor: %",
        "download" to "İndir",
        "meditation_timer" to "Tefekkür Zamanlayıcı",
        "meditated_minutes" to "Kaç Dakika Tefekkür Edildi?",
        "record_session" to "Tefekkürü Kaydet",
        "session_recorded" to "Tefekkür oturumu başarıyla kaydedildi!",
        "select_surah" to "Sure Seçin",
        "search_surah" to "Sure ara (örn: Fatiha, Yasin)...",
        "revelation_meccan" to "Mekkî",
        "revelation_medinan" to "Medenî",
        "bilingual" to "İki Dilli",
        "original" to "Orijinal",
        "turkish" to "Türkçe",
        "english" to "İngilizce",
        "play_audio" to "Sesi Oynat",
        "pause_audio" to "Duraklat",
        "stop_audio" to "Durdur",
        "live_api" to "Canlı API Entegrasyonu",
        "offline_cached" to "Gömülü Çevrimdışı Metin (Türkçe & Orijinal Dil)",
        "library_promo" to "Kutsal kitaplar, felsefi metinler ve ikincil kaynakların kütüphanesi.",
        "welcome" to "Hoş Geldiniz",
        "guest" to "Misafir Kullanıcı",
        "notifications" to "Bildirimler",
        "daily_notif_desc" to "Günde bir kez rastgele bir bilgelik ayeti bildirimi alırsınız.",
        "theme_antik" to "Klasik Antik",
        "greetings_journey" to "Bilgelik yolculuğunuza devam edin",
        "continue_reading" to "Okumaya Devam Et",
        "last_read" to "Son Okunan",
        "clean_history" to "Tüm Geçmişi Temizle",
        "no_history" to "Henüz okuma geçmişi bulunmuyor. Kütüphaneden kutsal metinleri okuyarak başlayabilirsiniz.",
        "verses" to "Ayet",
        "chapters" to "Bölüm",
        "surah" to "Sure",
        "bible_promo_desc" to "Kutsal metinler ve tefekkür külliyatı.",
        "select_bible_book" to "Kitab-ı Mukaddes Kitabı Seçin",
        "search_bible_book" to "Kitap ara (örn: Matta, Yaratılış)...",
        "talmud" to "Talmud (Babil Talmudu)",
        "bukhari" to "Sahih-i Buharî",
        "gita" to "Bhagavad Gita",
        "quran_short" to "Kur'an",
        "torah_short" to "Tevrat",
        "gospel_short" to "İncil",
        "psalms_short" to "Zebur",
        "gita_short" to "Gita"
    )

    private val en = mapOf(
        "home" to "Home",
        "library" to "Library",
        "miracles" to "Miracles",
        "dictionary" to "Dictionary",
        "search" to "Search",
        "profile" to "Profile",
        "settings" to "Settings",
        "appearance_settings" to "Appearance Settings",
        "preview" to "PREVIEW",
        "theme" to "THEME",
        "light" to "Light",
        "dark" to "Dark",
        "sepia" to "Sepia",
        "font_size" to "TEXT SIZE",
        "font_family" to "FONT FAMILY",
        "line_height" to "LINE HEIGHT",
        "tight" to "Tight",
        "normal" to "Medium",
        "wide" to "Wide",
        "app_language" to "APPLICATION LANGUAGE",
        "language_tr" to "Turkish (TR)",
        "language_en" to "English (EN)",
        "daily_verse" to "DAILY VERSE OF THE DAY",
        "refresh_verse" to "Refresh Verse",
        "reading_history" to "Reading History",
        "notes_highlights" to "Notes & Highlights",
        "stats" to "STATISTICS",
        "pages_read" to "Verses/Chapters Read",
        "books_completed" to "Completed Books",
        "active_days" to "Active Day Streak",
        "all_scriptures" to "Holy Scriptures",
        "quran" to "The Holy Quran",
        "torah" to "The Torah",
        "gospel" to "The Gospel",
        "sermon" to "The Gospel",
        "bible" to "The Bible",
        "search_hint" to "Search verses, chapters, topics or words...",
        "recent_searches" to "Recent Searches",
        "clear" to "Clear",
        "no_results" to "No results found",
        "search_results" to "Search Results",
        "notes" to "Notes",
        "highlights" to "Highlights",
        "no_notes" to "No notes added yet.",
        "no_highlights" to "No highlights added yet.",
        "add_note" to "Add Note",
        "edit_note" to "Edit Note",
        "save" to "Save",
        "cancel" to "Cancel",
        "delete" to "Delete",
        "read" to "Read",
        "back" to "Back",
        "all_verses_offline" to "All Chapters Offline!",
        "download_all_offline" to "Download Entire Book Offline",
        "quran_download_desc" to "All chapters have been saved locally with Arabic and English/Turkish translations. Read offline anytime.",
        "quran_download_promo" to "The holy book of Islam.",
        "downloading" to "Downloading: %",
        "download" to "Download",
        "meditation_timer" to "Meditation Timer",
        "meditated_minutes" to "How many minutes did you meditate?",
        "record_session" to "Record Meditation",
        "session_recorded" to "Meditation session successfully recorded!",
        "select_surah" to "Select Surah",
        "search_surah" to "Search surah (e.g., Fatihah, Ya-Sin)...",
        "revelation_meccan" to "Meccan",
        "revelation_medinan" to "Medinan",
        "bilingual" to "Bilingual",
        "original" to "Original",
        "turkish" to "Turkish",
        "english" to "English",
        "play_audio" to "Play Audio",
        "pause_audio" to "Pause",
        "stop_audio" to "Stop",
        "live_api" to "Live API Integration",
        "offline_cached" to "Embedded Offline Text (English & Original)",
        "library_promo" to "Library of sacred scriptures, philosophical texts, and secondary sources.",
        "welcome" to "Welcome",
        "guest" to "Guest Traveller",
        "notifications" to "Notifications",
        "daily_notif_desc" to "Receive a daily notification with a random wisdom verse.",
        "theme_antik" to "Classic Sepia",
        "greetings_journey" to "Continue your journey of wisdom",
        "continue_reading" to "Continue Reading",
        "last_read" to "Last Read",
        "clean_history" to "Clear All History",
        "no_history" to "No reading history yet. Start by exploring holy texts from the Library.",
        "verses" to "Verse",
        "chapters" to "Chapter",
        "surah" to "Surah",
        "bible_promo_desc" to "Sacred texts and spiritual scriptures.",
        "select_bible_book" to "Select Bible Book",
        "search_bible_book" to "Search book (e.g., Matthew, Genesis)...",
        "talmud" to "Talmud (Babylonian)",
        "bukhari" to "Sahih al-Bukhari",
        "gita" to "Bhagavad Gita",
        "quran_short" to "Quran",
        "torah_short" to "Torah",
        "gospel_short" to "Gospel",
        "psalms_short" to "Psalms",
        "gita_short" to "Gita"
    )

    fun get(key: String, lang: AppLanguage): String {
        return if (lang == AppLanguage.EN) en[key] ?: tr[key] ?: key else tr[key] ?: key
    }
}
